# Generated by Django 5.2.7 on 2025-11-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='images/default2.jpg', null=True, upload_to='images/'),
        ),
    ]
